from collections import namedtuple

CellSpec = namedtuple('CellSpec',
                      'line field literal field_type bytes columns cell')

user_print_file_spec = {('', 'Left printer alignment block'): CellSpec(line=1, field=(), literal='Left printer alignment block', field_type='M', bytes=3, columns=[1, 3], cell=(23, 3)),
 ('', 'Right printer alignment block'): CellSpec(line=1, field=(), literal='Right printer alignment block', field_type='M', bytes=3, columns=[77, 79], cell=(23, 231)),
 ('1', 'Champva'): CellSpec(line=3, field=(1, '1'), literal='Champva', field_type='M', bytes=1, columns=[24], cell=(31, 71)),
 ('1', 'FECA Blk Lung'): CellSpec(line=3, field=(1, '1'), literal='FECA Blk Lung', field_type='M', bytes=1, columns=[39], cell=(31, 117)),
 ('1', 'Group Health Plan'): CellSpec(line=3, field=(1, '1'), literal='Group Health Plan', field_type='M', bytes=1, columns=[31], cell=(31, 93)),
 ('1', 'Medicaid'): CellSpec(line=3, field=(1, '1'), literal='Medicaid', field_type='M', bytes=1, columns=[8], cell=(31, 23)),
 ('1', 'Medicare'): CellSpec(line=3, field=(1, '1'), literal='Medicare', field_type='M', bytes=1, columns=[1], cell=(31, 3)),
 ('1', 'Other'): CellSpec(line=3, field=(1, '1'), literal='Other', field_type='M', bytes=1, columns=[45], cell=(31, 134)),
 ('1', 'Tricare Champus'): CellSpec(line=3, field=(1, '1'), literal='Tricare Champus', field_type='M', bytes=1, columns=[15], cell=(31, 44)),
 ('10a', 'Condition Related (Employment C/P, No)'): CellSpec(line=15, field=(10, '10a'), literal='Condition Related (Employment C/P, No)', field_type='M', bytes=1, columns=[41], cell=(82, 123)),
 ('10a', 'Condition Related (Employment C/P, Yes)'): CellSpec(line=15, field=(10, '10a'), literal='Condition Related (Employment C/P, Yes)', field_type='M', bytes=1, columns=[35], cell=(82, 105)),
 ('10b', 'Condition Related To: (Auto Accident-No)'): CellSpec(line=17, field=(10, '10b'), literal='Condition Related To: (Auto Accident-No)', field_type='M', bytes=1, columns=[41], cell=(90, 123)),
 ('10b', 'Condition Related To: (Auto Accident-State)'): CellSpec(line=17, field=(10, '10b'), literal='Condition Related To: (Auto Accident-State)', field_type='A', bytes=2, columns=[45, 46], cell=(90, 135)),
 ('10b', 'Condition Related To: (Auto Accident-Yes)'): CellSpec(line=17, field=(10, '10b'), literal='Condition Related To: (Auto Accident-Yes)', field_type='M', bytes=1, columns=[35], cell=(90, 105)),
 ('10c', 'Other Accident (No)'): CellSpec(line=19, field=(10, '10c'), literal='Other Accident (No)', field_type='M', bytes=1, columns=[41], cell=(98, 123)),
 ('10c', 'Other Accident (Yes)'): CellSpec(line=19, field=(10, '10c'), literal='Other Accident (Yes)', field_type='M', bytes=1, columns=[35], cell=(98, 105)),
 ('10d', '(Reserved for Local Use)'): CellSpec(line=21, field=(10, '10d'), literal='(Reserved for Local Use)', field_type='A/N', bytes=19, columns=[30, 48], cell=(106, 90)),
 ('11', "Insured's Policy, Group or FECA Number"): CellSpec(line=13, field=(11, '11'), literal="Insured's Policy, Group or FECA Number", field_type='A/N', bytes=29, columns=[50, 78], cell=(73, 151)),
 ('11a', "Insured's Date of Birth (Day)"): CellSpec(line=15, field=(11, '11a'), literal="Insured's Date of Birth (Day)", field_type='N', bytes=2, columns=[56, 57], cell=(82, 167)),
 ('11a', "Insured's Date of Birth (Month)"): CellSpec(line=15, field=(11, '11a'), literal="Insured's Date of Birth (Month)", field_type='N', bytes=2, columns=[53, 54], cell=(82, 159)),
 ('11a', "Insured's Date of Birth (Year)"): CellSpec(line=15, field=(11, '11a'), literal="Insured's Date of Birth (Year)", field_type='N', bytes=4, columns=[59, 62], cell=(82, 177)),
 ('11a', 'Sex-Female'): CellSpec(line=15, field=(11, '11a'), literal='Sex-Female', field_type='M', bytes=1, columns=[75], cell=(82, 225)),
 ('11a', 'Sex-Male'): CellSpec(line=15, field=(11, '11a'), literal='Sex-Male', field_type='M', bytes=1, columns=[68], cell=(82, 203)),
 ('11b', "Insured's Employer's Name or School Name"): CellSpec(line=17, field=(11, '11b'), literal="Insured's Employer's Name or School Name", field_type='A/N', bytes=29, columns=[50, 78], cell=(90, 151)),
 ('11c', "Insured's Insurance Plan or PayerID"): CellSpec(line=19, field=(11, '11c'), literal="Insured's Insurance Plan or PayerID", field_type='A/N', bytes=29, columns=[50, 78], cell=(98, 151)),
 ('11d', 'Another Benefit Health Plan (No)'): CellSpec(line=21, field=(11, '11d'), literal='Another Benefit Health Plan (No)', field_type='M', bytes=1, columns=[57], cell=(106, 171)),
 ('11d', 'Another Benefit Health Plan (Yes)'): CellSpec(line=21, field=(11, '11d'), literal='Another Benefit Health Plan (Yes)', field_type='M', bytes=1, columns=[52], cell=(106, 156)),
 ('14', 'Date of Current Illness, Injury, Pregnancy (Day)'): CellSpec(line=27, field=(14, '14'), literal='Date of Current Illness, Injury, Pregnancy (Day)', field_type='N', bytes=2, columns=[5, 6], cell=None),
 ('14', 'Date of Current Illness, Injury, Pregnancy (Month)'): CellSpec(line=27, field=(14, '14'), literal='Date of Current Illness, Injury, Pregnancy (Month)', field_type='N', bytes=2, columns=[2, 3], cell=None),
 ('14', 'Date of Current Illness, Injury, Pregnancy -\n              (Year) N'): CellSpec(line=27, field=(14, '14'), literal='Date of Current Illness, Injury, Pregnancy -\n              (Year) N', field_type='', bytes=4, columns=[8, 11], cell=None),
 ('15', 'First Date Has Had Same or Similar Illness\n              (Month)N'): CellSpec(line=27, field=(15, '15'), literal='First Date Has Had Same or Similar Illness\n              (Month)N', field_type='', bytes=2, columns=[37, 38], cell=None),
 ('15', 'First Date Has Had Same or Similar Illness (Day) N'): CellSpec(line=27, field=(15, '15'), literal='First Date Has Had Same or Similar Illness (Day) N', field_type='', bytes=2, columns=[40, 41], cell=None),
 ('15', 'First Date Has Had Same or Similar Illness -\n              (Year) N'): CellSpec(line=27, field=(15, '15'), literal='First Date Has Had Same or Similar Illness -\n              (Year) N', field_type='', bytes=4, columns=[43, 46], cell=None),
 ('16', 'Dates Patient Unable to Work (From Day)'): CellSpec(line=27, field=(16, '16'), literal='Dates Patient Unable to Work (From Day)', field_type='N', bytes=2, columns=[57, 58], cell=None),
 ('16', 'Dates Patient Unable to Work (From Month)'): CellSpec(line=27, field=(16, '16'), literal='Dates Patient Unable to Work (From Month)', field_type='N', bytes=2, columns=[54, 55], cell=None),
 ('16', 'Dates Patient Unable to Work (From Year)'): CellSpec(line=27, field=(16, '16'), literal='Dates Patient Unable to Work (From Year)', field_type='N', bytes=4, columns=[60, 63], cell=None),
 ('16', 'Dates Patient Unable to Work (To Day)'): CellSpec(line=27, field=(16, '16'), literal='Dates Patient Unable to Work (To Day)', field_type='N', bytes=2, columns=[71, 72], cell=None),
 ('16', 'Dates Patient Unable to Work (To Month)'): CellSpec(line=27, field=(16, '16'), literal='Dates Patient Unable to Work (To Month)', field_type='N', bytes=2, columns=[68, 69], cell=None),
 ('16', 'Dates Patient Unable to Work (To Year)'): CellSpec(line=27, field=(16, '16'), literal='Dates Patient Unable to Work (To Year)', field_type='N', bytes=4, columns=[74, 77], cell=None),
 ('17', 'Name of Referring Physician or Other Source'): CellSpec(line=29, field=(17, '17'), literal='Name of Referring Physician or Other Source', field_type='A', bytes=26, columns=[1, 26], cell=None),
 ('17a', 'Legacy Qualifier/Provider Number of Referring Physician'): CellSpec(line=28, field=(17, '17a'), literal='Legacy Qualifier/Provider Number of Referring Physician', field_type='A/N', bytes=19, columns=[30, 48], cell=None),
 ('17b', 'NPI Number of Referring Physician'): CellSpec(line=29, field=(17, '17b'), literal='NPI Number of Referring Physician', field_type='N', bytes=17, columns=[32, 48], cell=(136, 95)),
 ('18', 'Hospitalization Related Current Svcs (From Day)'): CellSpec(line=29, field=(18, '18'), literal='Hospitalization Related Current Svcs (From Day)', field_type='N', bytes=2, columns=[57, 58], cell=None),
 ('18', 'Hospitalization Related Current Svcs (From Month)'): CellSpec(line=29, field=(18, '18'), literal='Hospitalization Related Current Svcs (From Month)', field_type='N', bytes=2, columns=[54, 55], cell=None),
 ('18', 'Hospitalization Related Current Svcs (From Year)'): CellSpec(line=29, field=(18, '18'), literal='Hospitalization Related Current Svcs (From Year)', field_type='N', bytes=4, columns=[60, 63], cell=(135, 181)),
 ('18', 'Hospitalization Related Current Svcs (To Day)'): CellSpec(line=29, field=(18, '18'), literal='Hospitalization Related Current Svcs (To Day)', field_type='N', bytes=2, columns=[71, 72], cell=(135, 213)),
 ('18', 'Hospitalization Related Current Svcs (To Month)'): CellSpec(line=29, field=(18, '18'), literal='Hospitalization Related Current Svcs (To Month)', field_type='N', bytes=2, columns=[68, 69], cell=(135, 203)),
 ('18', 'Hospitalization Related Current Svcs (To Year)'): CellSpec(line=29, field=(18, '18'), literal='Hospitalization Related Current Svcs (To Year)', field_type='N', bytes=4, columns=[74, 77], cell=(135, 222)),
 ('19', 'Reserved for Local Use'): CellSpec(line=31, field=(19, '19'), literal='Reserved for Local Use', field_type='A/N', bytes=48, columns=[1, 48], cell=None),
 ('1a', "Insured's ID Number"): CellSpec(line=3, field=(1, '1a'), literal="Insured's ID Number", field_type='A/N', bytes=29, columns=[50, 78], cell=(31, 151)),
 ('2', "Patient's Name (Last, First, MI)"): CellSpec(line=5, field=(2, '2'), literal="Patient's Name (Last, First, MI)", field_type='A', bytes=28, columns=[1, 28], cell=(39, 4)),
 ('20', '$ Charges'): CellSpec(line=31, field=(20, '20'), literal='$ Charges', field_type='N', bytes=8, columns=[62, 78], cell=(143, 185)),
 ('20', 'Outside Lab (No)'): CellSpec(line=31, field=(20, '20'), literal='Outside Lab (No)', field_type='M', bytes=1, columns=[57], cell=None),
 ('20', 'Outside Lab (Yes)'): CellSpec(line=31, field=(20, '20'), literal='Outside Lab (Yes)', field_type='M', bytes=1, columns=[52], cell=None),
 ('21.1', 'Diagnosis or Nature of Illness or Injury (Code)'): CellSpec(line=33, field=(21, '21.1'), literal='Diagnosis or Nature of Illness or Injury (Code)', field_type='A/N', bytes=8, columns=[3, 10], cell=(156, 8)),
 ('21.2', 'Diagnosis or Nature of Illness or Injury (Code)'): CellSpec(line=35, field=(21, '21.2'), literal='Diagnosis or Nature of Illness or Injury (Code)', field_type='A/N', bytes=8, columns=[3, 10], cell=(164, 8)),
 ('21.3', 'Diagnosis or Nature of Illness or Injury (Code)'): CellSpec(line=33, field=(21, '21.3'), literal='Diagnosis or Nature of Illness or Injury (Code)', field_type='A/N', bytes=8, columns=[30, 37], cell=(151, 89)),
 ('21.4', 'Diagnosis or Nature of Illness or Injury (Code)'): CellSpec(line=35, field=(21, '21.4'), literal='Diagnosis or Nature of Illness or Injury (Code)', field_type='A/N', bytes=8, columns=[30, 37], cell=(159, 91)),
 ('22', 'Medicaid Resubmission Code'): CellSpec(line=33, field=(22, '22'), literal='Medicaid Resubmission Code', field_type='A/N', bytes=11, columns=[50, 60], cell=None),
 ('22.2', 'Original Reference Number'): CellSpec(line=33, field=(22, '22.2'), literal='Original Reference Number', field_type='A/N', bytes=18, columns=[61, 78], cell=(151, 184)),
 ('23', 'Prior Authorization Number'): CellSpec(line=35, field=(23, '23'), literal='Prior Authorization Number', field_type='A/N', bytes=29, columns=[50, 78], cell=(159, 151)),
 ('24', 'Line Detail Narrative'): CellSpec(line=48, field=(24, '24'), literal='Line Detail Narrative', field_type='A/N', bytes=63, columns=[1, 63], cell=(211, 3)),
 ('24.1a', 'Date(s) of Service - (From Day)'): CellSpec(line=39, field=(24, '24.1a'), literal='Date(s) of Service - (From Day)', field_type='N', bytes=2, columns=[4, 5], cell=(178, 11)),
 ('24.1a', 'Date(s) of Service - (From Month)'): CellSpec(line=39, field=(24, '24.1a'), literal='Date(s) of Service - (From Month)', field_type='N', bytes=2, columns=[1, 2], cell=(178, 3)),
 ('24.1a', 'Date(s) of Service - (From Year)'): CellSpec(line=39, field=(24, '24.1a'), literal='Date(s) of Service - (From Year)', field_type='N', bytes=2, columns=[7, 8], cell=(178, 20)),
 ('24.1a', 'Date(s) of Service - (To Day)'): CellSpec(line=39, field=(24, '24.1a'), literal='Date(s) of Service - (To Day)', field_type='N', bytes=2, columns=[13, 14], cell=(178, 38)),
 ('24.1a', 'Date(s) of Service - (To Month)'): CellSpec(line=39, field=(24, '24.1a'), literal='Date(s) of Service - (To Month)', field_type='N', bytes=2, columns=[10, 11], cell=(178, 29)),
 ('24.1a', 'Date(s) of Service - (To Year)'): CellSpec(line=39, field=(24, '24.1a'), literal='Date(s) of Service - (To Year)', field_type='N', bytes=2, columns=[16, 17], cell=(178, 47)),
 ('24.1b', 'Place of Service'): CellSpec(line=39, field=(24, '24.1b'), literal='Place of Service', field_type='A/N', bytes=2, columns=[19, 20], cell=(178, 56)),
 ('24.1c', 'EMG'): CellSpec(line=39, field=(24, '24.1c'), literal='EMG', field_type='A', bytes=2, columns=[22, 23], cell=(178, 65)),
 ('24.1d', 'Procedures, Svcs or Supplies (CPT/HCPCS)'): CellSpec(line=39, field=(24, '24.1d'), literal='Procedures, Svcs or Supplies (CPT/HCPCS)', field_type='A/N', bytes=6, columns=[25, 30], cell=(178, 74)),
 ('24.1d', 'Procedures, Svcs or Supplies (Modifier 1)'): CellSpec(line=39, field=(24, '24.1d'), literal='Procedures, Svcs or Supplies (Modifier 1)', field_type='A/N', bytes=2, columns=[33, 34], cell=(178, 98)),
 ('24.1d', 'Procedures, Svcs or Supplies (Modifier 2)'): CellSpec(line=39, field=(24, '24.1d'), literal='Procedures, Svcs or Supplies (Modifier 2)', field_type='A/N', bytes=2, columns=[36, 37], cell=(178, 107)),
 ('24.1d', 'Procedures, Svcs or Supplies (Modifier 3)'): CellSpec(line=39, field=(24, '24.1d'), literal='Procedures, Svcs or Supplies (Modifier 3)', field_type='A/N', bytes=2, columns=[39, 40], cell=(178, 116)),
 ('24.1d', 'Procedures, Svcs or Supplies (Modifier 4)'): CellSpec(line=39, field=(24, '24.1d'), literal='Procedures, Svcs or Supplies (Modifier 4)', field_type='A/N', bytes=2, columns=[42, 43], cell=(178, 125)),
 ('24.1e', 'Diagnosis Pointer'): CellSpec(line=39, field=(24, '24.1e'), literal='Diagnosis Pointer', field_type='N', bytes=4, columns=[45, 48], cell=(178, 134)),
 ('24.1f', '$ Charges'): CellSpec(line=39, field=(24, '24.1f'), literal='$ Charges', field_type='N', bytes=8, columns=[50, 57], cell=(178, 149)),
 ('24.1g', 'Days or Units'): CellSpec(line=39, field=(24, '24.1g'), literal='Days or Units', field_type='N', bytes=3, columns=[59, 61], cell=(178, 176)),
 ('24.1h', 'EPSDT Family Plan'): CellSpec(line=39, field=(24, '24.1h'), literal='EPSDT Family Plan', field_type='A', bytes=1, columns=[63], cell=(178, 188)),
 ('24.1i', 'Legacy Qualifier Rendering Provider'): CellSpec(line=38, field=(24, '24.1i'), literal='Legacy Qualifier Rendering Provider', field_type='A/N', bytes=2, columns=[65, 66], cell=None),
 ('24.1j', 'Legacy Provider Number Rendering Provider'): CellSpec(line=39, field=(24, '24.1j'), literal='Legacy Provider Number Rendering Provider', field_type='A/N', bytes=11, columns=[68, 78], cell=(178, 203)),
 ('24.2a', 'Date(s) of Service - (From Day)'): CellSpec(line=41, field=(24, '24.2a'), literal='Date(s) of Service - (From Day)', field_type='N', bytes=2, columns=[4, 5], cell=(183, 11)),
 ('24.2a', 'Date(s) of Service - (From Month)'): CellSpec(line=41, field=(24, '24.2a'), literal='Date(s) of Service - (From Month)', field_type='N', bytes=2, columns=[1, 2], cell=(183, 3)),
 ('24.2a', 'Date(s) of Service - (From Year)'): CellSpec(line=41, field=(24, '24.2a'), literal='Date(s) of Service - (From Year)', field_type='N', bytes=2, columns=[7, 8], cell=(183, 20)),
 ('24.2a', 'Date(s) of Service - (To Day)'): CellSpec(line=41, field=(24, '24.2a'), literal='Date(s) of Service - (To Day)', field_type='N', bytes=2, columns=[13, 14], cell=(183, 38)),
 ('24.2a', 'Date(s) of Service - (To Month)'): CellSpec(line=41, field=(24, '24.2a'), literal='Date(s) of Service - (To Month)', field_type='N', bytes=2, columns=[10, 11], cell=(183, 29)),
 ('24.2a', 'Date(s) of Service - (To Year)'): CellSpec(line=41, field=(24, '24.2a'), literal='Date(s) of Service - (To Year)', field_type='N', bytes=2, columns=[16, 17], cell=(183, 47)),
 ('24.2b', 'Place of Service'): CellSpec(line=41, field=(24, '24.2b'), literal='Place of Service', field_type='A/N', bytes=2, columns=[19, 20], cell=(183, 56)),
 ('24.2c', 'EMG'): CellSpec(line=41, field=(24, '24.2c'), literal='EMG', field_type='A', bytes=2, columns=[22, 23], cell=(183, 65)),
 ('24.2d', 'Procedures, Svcs or Supplies (CPT/HCPCS)'): CellSpec(line=41, field=(24, '24.2d'), literal='Procedures, Svcs or Supplies (CPT/HCPCS)', field_type='A/N', bytes=6, columns=[25, 30], cell=(183, 76)),
 ('24.2d', 'Procedures, Svcs or Supplies (Modifier 1)'): CellSpec(line=41, field=(24, '24.2d'), literal='Procedures, Svcs or Supplies (Modifier 1)', field_type='A/N', bytes=2, columns=[33, 34], cell=(183, 98)),
 ('24.2d', 'Procedures, Svcs or Supplies (Modifier 2)'): CellSpec(line=41, field=(24, '24.2d'), literal='Procedures, Svcs or Supplies (Modifier 2)', field_type='A/N', bytes=2, columns=[36, 37], cell=(183, 107)),
 ('24.2d', 'Procedures, Svcs or Supplies (Modifier 3)'): CellSpec(line=41, field=(24, '24.2d'), literal='Procedures, Svcs or Supplies (Modifier 3)', field_type='A/N', bytes=2, columns=[39, 40], cell=(183, 116)),
 ('24.2d', 'Procedures, Svcs or Supplies (Modifier 4)'): CellSpec(line=41, field=(24, '24.2d'), literal='Procedures, Svcs or Supplies (Modifier 4)', field_type='A/N', bytes=2, columns=[42, 43], cell=(183, 125)),
 ('24.2e', 'Diagnosis Pointer'): CellSpec(line=41, field=(24, '24.2e'), literal='Diagnosis Pointer', field_type='N', bytes=4, columns=[45, 48], cell=(183, 134)),
 ('24.2f', '$ Charges'): CellSpec(line=41, field=(24, '24.2f'), literal='$ Charges', field_type='N', bytes=8, columns=[50, 57], cell=(183, 151)),
 ('24.2g', 'Days or Units'): CellSpec(line=41, field=(24, '24.2g'), literal='Days or Units', field_type='N', bytes=3, columns=[59, 61], cell=(183, 177)),
 ('24.2h', 'EPSDT Family Plan'): CellSpec(line=41, field=(24, '24.2h'), literal='EPSDT Family Plan', field_type='A', bytes=1, columns=[63], cell=(183, 188)),
 ('24.2i', 'Legacy Qualifier Rendering Provider'): CellSpec(line=40, field=(24, '24.2i'), literal='Legacy Qualifier Rendering Provider', field_type='A/N', bytes=2, columns=[65, 66], cell=(179, 194)),
 ('24.2j', 'Legacy Provider Number Rendering Provider'): CellSpec(line=41, field=(24, '24.2j'), literal='Legacy Provider Number Rendering Provider', field_type='A/N', bytes=11, columns=[68, 78], cell=(183, 203)),
 ('24.3a', 'Date(s) of Service - (From Day)'): CellSpec(line=43, field=(24, '24.3a'), literal='Date(s) of Service - (From Day)', field_type='N', bytes=2, columns=[4, 5], cell=(191, 11)),
 ('24.3a', 'Date(s) of Service - (From Month)'): CellSpec(line=43, field=(24, '24.3a'), literal='Date(s) of Service - (From Month)', field_type='N', bytes=2, columns=[1, 2], cell=(191, 3)),
 ('24.3a', 'Date(s) of Service - (From Year)'): CellSpec(line=43, field=(24, '24.3a'), literal='Date(s) of Service - (From Year)', field_type='N', bytes=2, columns=[7, 8], cell=(191, 20)),
 ('24.3a', 'Date(s) of Service - (To Day)'): CellSpec(line=43, field=(24, '24.3a'), literal='Date(s) of Service - (To Day)', field_type='N', bytes=2, columns=[13, 14], cell=(191, 38)),
 ('24.3a', 'Date(s) of Service - (To Month)'): CellSpec(line=43, field=(24, '24.3a'), literal='Date(s) of Service - (To Month)', field_type='N', bytes=2, columns=[10, 11], cell=(191, 29)),
 ('24.3a', 'Date(s) of Service - (To Year)'): CellSpec(line=43, field=(24, '24.3a'), literal='Date(s) of Service - (To Year)', field_type='N', bytes=2, columns=[16, 17], cell=(191, 47)),
 ('24.3b', 'Place of Service'): CellSpec(line=43, field=(24, '24.3b'), literal='Place of Service', field_type='A/N', bytes=2, columns=[19, 20], cell=(191, 56)),
 ('24.3c', 'EMG'): CellSpec(line=43, field=(24, '24.3c'), literal='EMG', field_type='A', bytes=2, columns=[22, 23], cell=(191, 65)),
 ('24.3d', 'Procedures, Svcs or Supplies (CPT/HCPCS)'): CellSpec(line=43, field=(24, '24.3d'), literal='Procedures, Svcs or Supplies (CPT/HCPCS)', field_type='A/N', bytes=6, columns=[25, 30], cell=(191, 76)),
 ('24.3d', 'Procedures, Svcs or Supplies (Modifier 1)'): CellSpec(line=43, field=(24, '24.3d'), literal='Procedures, Svcs or Supplies (Modifier 1)', field_type='A/N', bytes=2, columns=[33, 34], cell=(191, 98)),
 ('24.3d', 'Procedures, Svcs or Supplies (Modifier 2)'): CellSpec(line=43, field=(24, '24.3d'), literal='Procedures, Svcs or Supplies (Modifier 2)', field_type='A/N', bytes=2, columns=[36, 37], cell=(191, 107)),
 ('24.3d', 'Procedures, Svcs or Supplies (Modifier 3)'): CellSpec(line=43, field=(24, '24.3d'), literal='Procedures, Svcs or Supplies (Modifier 3)', field_type='A/N', bytes=2, columns=[39, 40], cell=(191, 116)),
 ('24.3d', 'Procedures, Svcs or Supplies (Modifier 4)'): CellSpec(line=43, field=(24, '24.3d'), literal='Procedures, Svcs or Supplies (Modifier 4)', field_type='A/N', bytes=2, columns=[42, 43], cell=(191, 125)),
 ('24.3e', 'Diagnosis Pointer'): CellSpec(line=43, field=(24, '24.3e'), literal='Diagnosis Pointer', field_type='N', bytes=4, columns=[45, 48], cell=(191, 134)),
 ('24.3f', '$ Charges'): CellSpec(line=43, field=(24, '24.3f'), literal='$ Charges', field_type='N', bytes=8, columns=[50, 57], cell=(191, 151)),
 ('24.3g', 'Days or Units'): CellSpec(line=43, field=(24, '24.3g'), literal='Days or Units', field_type='N', bytes=3, columns=[59, 61], cell=(191, 177)),
 ('24.3h', 'EPSDT Family Plan'): CellSpec(line=43, field=(24, '24.3h'), literal='EPSDT Family Plan', field_type='A', bytes=1, columns=[63], cell=(191, 188)),
 ('24.3i', 'Legacy Qualifier Rendering Provider'): CellSpec(line=42, field=(24, '24.3i'), literal='Legacy Qualifier Rendering Provider', field_type='A/N', bytes=2, columns=[65, 66], cell=(187, 194)),
 ('24.3j', 'Legacy Provider Number Rendering Provider'): CellSpec(line=43, field=(24, '24.3j'), literal='Legacy Provider Number Rendering Provider', field_type='A/N', bytes=11, columns=[68, 78], cell=(191, 203)),
 ('24.4a', 'Date(s) of Service - (From Day)'): CellSpec(line=45, field=(24, '24.4a'), literal='Date(s) of Service - (From Day)', field_type='N', bytes=2, columns=[4, 5], cell=(199, 11)),
 ('24.4a', 'Date(s) of Service - (From Month)'): CellSpec(line=45, field=(24, '24.4a'), literal='Date(s) of Service - (From Month)', field_type='N', bytes=2, columns=[1, 2], cell=(199, 3)),
 ('24.4a', 'Date(s) of Service - (From Year)'): CellSpec(line=45, field=(24, '24.4a'), literal='Date(s) of Service - (From Year)', field_type='N', bytes=2, columns=[7, 8], cell=(199, 20)),
 ('24.4a', 'Date(s) of Service - (To Day)'): CellSpec(line=45, field=(24, '24.4a'), literal='Date(s) of Service - (To Day)', field_type='N', bytes=2, columns=[13, 14], cell=(199, 38)),
 ('24.4a', 'Date(s) of Service - (To Month)'): CellSpec(line=45, field=(24, '24.4a'), literal='Date(s) of Service - (To Month)', field_type='N', bytes=2, columns=[10, 11], cell=(199, 29)),
 ('24.4a', 'Date(s) of Service - (To Year)'): CellSpec(line=45, field=(24, '24.4a'), literal='Date(s) of Service - (To Year)', field_type='N', bytes=2, columns=[16, 17], cell=(199, 47)),
 ('24.4b', 'Place of Service'): CellSpec(line=45, field=(24, '24.4b'), literal='Place of Service', field_type='A/N', bytes=2, columns=[19, 20], cell=(199, 56)),
 ('24.4c', 'EMG'): CellSpec(line=45, field=(24, '24.4c'), literal='EMG', field_type='A', bytes=2, columns=[22, 23], cell=(199, 65)),
 ('24.4d', 'Procedures, Svcs or Supplies (CPT/HCPCS)'): CellSpec(line=45, field=(24, '24.4d'), literal='Procedures, Svcs or Supplies (CPT/HCPCS)', field_type='A/N', bytes=6, columns=[25, 30], cell=(199, 76)),
 ('24.4d', 'Procedures, Svcs or Supplies (Modifier 1)'): CellSpec(line=45, field=(24, '24.4d'), literal='Procedures, Svcs or Supplies (Modifier 1)', field_type='A/N', bytes=2, columns=[33, 34], cell=(199, 98)),
 ('24.4d', 'Procedures, Svcs or Supplies (Modifier 2)'): CellSpec(line=45, field=(24, '24.4d'), literal='Procedures, Svcs or Supplies (Modifier 2)', field_type='A/N', bytes=2, columns=[36, 37], cell=(199, 107)),
 ('24.4d', 'Procedures, Svcs or Supplies (Modifier 3)'): CellSpec(line=45, field=(24, '24.4d'), literal='Procedures, Svcs or Supplies (Modifier 3)', field_type='A/N', bytes=2, columns=[39, 40], cell=(199, 116)),
 ('24.4d', 'Procedures, Svcs or Supplies (Modifier 4)'): CellSpec(line=45, field=(24, '24.4d'), literal='Procedures, Svcs or Supplies (Modifier 4)', field_type='A/N', bytes=2, columns=[42, 43], cell=(199, 125)),
 ('24.4e', 'Diagnosis Pointer'): CellSpec(line=45, field=(24, '24.4e'), literal='Diagnosis Pointer', field_type='N', bytes=4, columns=[45, 48], cell=(199, 134)),
 ('24.4f', '$ Charges'): CellSpec(line=45, field=(24, '24.4f'), literal='$ Charges', field_type='N', bytes=8, columns=[50, 57], cell=(199, 151)),
 ('24.4g', 'Days or Units'): CellSpec(line=45, field=(24, '24.4g'), literal='Days or Units', field_type='N', bytes=3, columns=[59, 61], cell=(199, 177)),
 ('24.4h', 'EPSDT Family Plan'): CellSpec(line=45, field=(24, '24.4h'), literal='EPSDT Family Plan', field_type='A', bytes=1, columns=[63], cell=(199, 188)),
 ('24.4i', 'Legacy Qualifier Rendering Provider'): CellSpec(line=44, field=(24, '24.4i'), literal='Legacy Qualifier Rendering Provider', field_type='A/N', bytes=2, columns=[65, 66], cell=(195, 194)),
 ('24.4j', 'Legacy Provider Number Rendering Provider'): CellSpec(line=45, field=(24, '24.4j'), literal='Legacy Provider Number Rendering Provider', field_type='A/N', bytes=11, columns=[68, 78], cell=(199, 203)),
 ('24.5a', 'Date(s) of Service - (From Day)'): CellSpec(line=47, field=(24, '24.5a'), literal='Date(s) of Service - (From Day)', field_type='N', bytes=2, columns=[4, 5], cell=(207, 11)),
 ('24.5a', 'Date(s) of Service - (From Month)'): CellSpec(line=47, field=(24, '24.5a'), literal='Date(s) of Service - (From Month)', field_type='N', bytes=2, columns=[1, 2], cell=(207, 3)),
 ('24.5a', 'Date(s) of Service - (From Year)'): CellSpec(line=47, field=(24, '24.5a'), literal='Date(s) of Service - (From Year)', field_type='N', bytes=2, columns=[7, 8], cell=(207, 20)),
 ('24.5a', 'Date(s) of Service - (To Day)'): CellSpec(line=47, field=(24, '24.5a'), literal='Date(s) of Service - (To Day)', field_type='N', bytes=2, columns=[13, 14], cell=(207, 38)),
 ('24.5a', 'Date(s) of Service - (To Month)'): CellSpec(line=47, field=(24, '24.5a'), literal='Date(s) of Service - (To Month)', field_type='N', bytes=2, columns=[10, 11], cell=(207, 29)),
 ('24.5a', 'Date(s) of Service - (To Year)'): CellSpec(line=47, field=(24, '24.5a'), literal='Date(s) of Service - (To Year)', field_type='N', bytes=2, columns=[16, 17], cell=(207, 47)),
 ('24.5b', 'Place of Service'): CellSpec(line=47, field=(24, '24.5b'), literal='Place of Service', field_type='A/N', bytes=2, columns=[19, 20], cell=(207, 56)),
 ('24.5c', 'EMG'): CellSpec(line=47, field=(24, '24.5c'), literal='EMG', field_type='A', bytes=2, columns=[22, 23], cell=(207, 65)),
 ('24.5d', 'Procedures, Svcs or Supplies (CPT/HCPCS)'): CellSpec(line=47, field=(24, '24.5d'), literal='Procedures, Svcs or Supplies (CPT/HCPCS)', field_type='A/N', bytes=6, columns=[25, 30], cell=(207, 74)),
 ('24.5d', 'Procedures, Svcs or Supplies (Modifier 1)'): CellSpec(line=47, field=(24, '24.5d'), literal='Procedures, Svcs or Supplies (Modifier 1)', field_type='A/N', bytes=2, columns=[33, 34], cell=(207, 98)),
 ('24.5d', 'Procedures, Svcs or Supplies (Modifier 2)'): CellSpec(line=47, field=(24, '24.5d'), literal='Procedures, Svcs or Supplies (Modifier 2)', field_type='A/N', bytes=2, columns=[36, 37], cell=(207, 107)),
 ('24.5d', 'Procedures, Svcs or Supplies (Modifier 3)'): CellSpec(line=47, field=(24, '24.5d'), literal='Procedures, Svcs or Supplies (Modifier 3)', field_type='A/N', bytes=2, columns=[39, 40], cell=(207, 116)),
 ('24.5d', 'Procedures, Svcs or Supplies (Modifier 4)'): CellSpec(line=47, field=(24, '24.5d'), literal='Procedures, Svcs or Supplies (Modifier 4)', field_type='A/N', bytes=2, columns=[42, 43], cell=(207, 125)),
 ('24.5e', 'Diagnosis Pointer'): CellSpec(line=47, field=(24, '24.5e'), literal='Diagnosis Pointer', field_type='N', bytes=4, columns=[45, 48], cell=(207, 134)),
 ('24.5f', '$ Charges'): CellSpec(line=47, field=(24, '24.5f'), literal='$ Charges', field_type='N', bytes=8, columns=[50, 57], cell=(207, 149)),
 ('24.5g', 'Days or Units'): CellSpec(line=47, field=(24, '24.5g'), literal='Days or Units', field_type='N', bytes=3, columns=[59, 61], cell=(207, 176)),
 ('24.5h', 'EPSDT Family Plan'): CellSpec(line=47, field=(24, '24.5h'), literal='EPSDT Family Plan', field_type='A', bytes=1, columns=[63], cell=(207, 188)),
 ('24.5i', 'Legacy Qualifier Rendering Provider'): CellSpec(line=46, field=(24, '24.5i'), literal='Legacy Qualifier Rendering Provider', field_type='A/N', bytes=2, columns=[65, 66], cell=(203, 194)),
 ('24.5j', 'Legacy Provider Number Rendering Provider'): CellSpec(line=47, field=(24, '24.5j'), literal='Legacy Provider Number Rendering Provider', field_type='A/N', bytes=11, columns=[68, 78], cell=(207, 203)),
 ('24.6a', 'Date(s) of Service - (From Day)'): CellSpec(line=49, field=(24, '24.6a'), literal='Date(s) of Service - (From Day)', field_type='N', bytes=2, columns=[4, 5], cell=(215, 11)),
 ('24.6a', 'Date(s) of Service - (From Month)'): CellSpec(line=49, field=(24, '24.6a'), literal='Date(s) of Service - (From Month)', field_type='N', bytes=2, columns=[1, 2], cell=(215, 3)),
 ('24.6a', 'Date(s) of Service - (From Year)'): CellSpec(line=49, field=(24, '24.6a'), literal='Date(s) of Service - (From Year)', field_type='N', bytes=2, columns=[7, 8], cell=(215, 20)),
 ('24.6a', 'Date(s) of Service - (To Day)'): CellSpec(line=49, field=(24, '24.6a'), literal='Date(s) of Service - (To Day)', field_type='N', bytes=2, columns=[13, 14], cell=(215, 38)),
 ('24.6a', 'Date(s) of Service - (To Month)'): CellSpec(line=49, field=(24, '24.6a'), literal='Date(s) of Service - (To Month)', field_type='N', bytes=2, columns=[10, 11], cell=(215, 29)),
 ('24.6a', 'Date(s) of Service - (To Year)'): CellSpec(line=49, field=(24, '24.6a'), literal='Date(s) of Service - (To Year)', field_type='N', bytes=2, columns=[16, 17], cell=(215, 47)),
 ('24.6b', 'Place of Service'): CellSpec(line=49, field=(24, '24.6b'), literal='Place of Service', field_type='A/N', bytes=2, columns=[19, 20], cell=(215, 56)),
 ('24.6c', 'EMG'): CellSpec(line=49, field=(24, '24.6c'), literal='EMG', field_type='A', bytes=2, columns=[22, 23], cell=(215, 65)),
 ('24.6d', 'Procedures, Svcs or Supplies (CPT/HCPCS)'): CellSpec(line=49, field=(24, '24.6d'), literal='Procedures, Svcs or Supplies (CPT/HCPCS)', field_type='A/N', bytes=6, columns=[25, 30], cell=(215, 74)),
 ('24.6d', 'Procedures, Svcs or Supplies (Modifier 1)'): CellSpec(line=49, field=(24, '24.6d'), literal='Procedures, Svcs or Supplies (Modifier 1)', field_type='A/N', bytes=2, columns=[33, 34], cell=(215, 98)),
 ('24.6d', 'Procedures, Svcs or Supplies (Modifier 2)'): CellSpec(line=49, field=(24, '24.6d'), literal='Procedures, Svcs or Supplies (Modifier 2)', field_type='A/N', bytes=2, columns=[36, 37], cell=(215, 107)),
 ('24.6d', 'Procedures, Svcs or Supplies (Modifier 3)'): CellSpec(line=49, field=(24, '24.6d'), literal='Procedures, Svcs or Supplies (Modifier 3)', field_type='A/N', bytes=2, columns=[39, 40], cell=(215, 116)),
 ('24.6d', 'Procedures, Svcs or Supplies (Modifier 4)'): CellSpec(line=49, field=(24, '24.6d'), literal='Procedures, Svcs or Supplies (Modifier 4)', field_type='A/N', bytes=2, columns=[42, 43], cell=(215, 125)),
 ('24.6e', 'Diagnosis Pointer'): CellSpec(line=49, field=(24, '24.6e'), literal='Diagnosis Pointer', field_type='N', bytes=4, columns=[45, 48], cell=(215, 134)),
 ('24.6f', '$ Charges'): CellSpec(line=49, field=(24, '24.6f'), literal='$ Charges', field_type='N', bytes=8, columns=[50, 57], cell=(215, 149)),
 ('24.6g', 'Days or Units'): CellSpec(line=49, field=(24, '24.6g'), literal='Days or Units', field_type='N', bytes=3, columns=[59, 61], cell=(215, 176)),
 ('24.6h', 'EPSDT Family Plan'): CellSpec(line=49, field=(24, '24.6h'), literal='EPSDT Family Plan', field_type='A', bytes=1, columns=[63], cell=(215, 188)),
 ('24.6i', 'Legacy Qualifier Rendering Provider'): CellSpec(line=48, field=(24, '24.6i'), literal='Legacy Qualifier Rendering Provider', field_type='A/N', bytes=2, columns=[65, 66], cell=(211, 194)),
 ('24.6j', 'Legacy Provider Number Rendering Provider'): CellSpec(line=49, field=(24, '24.6j'), literal='Legacy Provider Number Rendering Provider', field_type='A/N', bytes=11, columns=[68, 78], cell=(215, 203)),
 ('25', 'Federal Tax ID Number'): CellSpec(line=51, field=(25, '25'), literal='Federal Tax ID Number', field_type='N', bytes=15, columns=[1, 15], cell=(223, 3)),
 ('25', 'Federal Tax ID Number (EIN)'): CellSpec(line=51, field=(25, '25'), literal='Federal Tax ID Number (EIN)', field_type='M', bytes=1, columns=[19], cell=(223, 56)),
 ('25', 'Federal Tax ID Number (SSN)'): CellSpec(line=51, field=(25, '25'), literal='Federal Tax ID Number (SSN)', field_type='M', bytes=1, columns=[17], cell=(223, 50)),
 ('26', "Patient's Account Number"): CellSpec(line=51, field=(26, '26'), literal="Patient's Account Number", field_type='A/N', bytes=14, columns=[23, 36], cell=(223, 68)),
 ('27', 'Accept Assignment (No)'): CellSpec(line=51, field=(27, '27'), literal='Accept Assignment (No)', field_type='M', bytes=1, columns=[43], cell=(223, 128)),
 ('27', 'Accept Assignment (Yes)'): CellSpec(line=51, field=(27, '27'), literal='Accept Assignment (Yes)', field_type='M', bytes=1, columns=[38], cell=(223, 113)),
 ('28', 'Total Charge'): CellSpec(line=51, field=(28, '28'), literal='Total Charge', field_type='N', bytes=9, columns=[51, 59], cell=(223, 152)),
 ('29', 'Amount Paid'): CellSpec(line=51, field=(29, '29'), literal='Amount Paid', field_type='N', bytes=8, columns=[62, 69], cell=(223, 185)),
 ('3', "Patient's Birth (Year)"): CellSpec(line=5, field=(3, '3'), literal="Patient's Birth (Year)", field_type='N', bytes=4, columns=[37, 40], cell=(40, 111)),
 ('3', "Patient's Birth Date (Day)"): CellSpec(line=5, field=(3, '3'), literal="Patient's Birth Date (Day)", field_type='N', bytes=2, columns=[34, 35], cell=(40, 102)),
 ('3', "Patient's Birth Date (Month)"): CellSpec(line=5, field=(3, '3'), literal="Patient's Birth Date (Month)", field_type='N', bytes=2, columns=[31, 32], cell=(40, 92)),
 ('3', 'Sex-Female'): CellSpec(line=5, field=(3, '3'), literal='Sex-Female', field_type='M', bytes=1, columns=[47], cell=(39, 141)),
 ('3', 'Sex-Male'): CellSpec(line=5, field=(3, '3'), literal='Sex-Male', field_type='M', bytes=1, columns=[42], cell=(39, 126)),
 ('30', 'Balance Due'): CellSpec(line=51, field=(30, '30'), literal='Balance Due', field_type='N', bytes=8, columns=[71, 78], cell=(223, 212)),
 ('32', 'Address of Facility Where Svcs Rendered'): CellSpec(line=54, field=(32, '32'), literal='Address of Facility Where Svcs Rendered', field_type='A/N', bytes=26, columns=[23, 48], cell=None),
 ('32', 'City, State and ZIP Code of Facility'): CellSpec(line=55, field=(32, '32'), literal='City, State and ZIP Code of Facility', field_type='A/N', bytes=26, columns=[23, 48], cell=None),
 ('32', 'Name of Facility Where Svcs Rendered'): CellSpec(line=53, field=(32, '32'), literal='Name of Facility Where Svcs Rendered', field_type='A/N', bytes=26, columns=[23, 48], cell=None),
 ('32a', 'Facility NPI Number'): CellSpec(line=56, field=(32, '32a'), literal='Facility NPI Number', field_type='N', bytes=10, columns=[24, 33], cell=(243, 72)),
 ('32b', 'Facility Qualifier and Legacy Number'): CellSpec(line=56, field=(32, '32b'), literal='Facility Qualifier and Legacy Number', field_type='A/N', bytes=14, columns=[35, 48], cell=(243, 104)),
 ('33', 'Billing Provider Phone Number'): CellSpec(line=52, field=(33, '33'), literal='Billing Provider Phone Number', field_type='N', bytes=9, columns=[70, 78], cell=(227, 209)),
 ('33', 'Billing Provider Phone Number Area Code'): CellSpec(line=52, field=(33, '33'), literal='Billing Provider Phone Number Area Code', field_type='N', bytes=3, columns=[66, 68], cell=None),
 ('33', 'City, State and ZIP Code of Billing Provider'): CellSpec(line=55, field=(33, '33'), literal='City, State and ZIP Code of Billing Provider', field_type='A/N', bytes=29, columns=[50, 78], cell=None),
 ('33', 'Physician/Supplier Address'): CellSpec(line=54, field=(33, '33'), literal='Physician/Supplier Address', field_type='A/N', bytes=29, columns=[50, 78], cell=None),
 ('33', 'Physician/Supplier Billing Name'): CellSpec(line=53, field=(33, '33'), literal='Physician/Supplier Billing Name', field_type='A/N', bytes=29, columns=[50, 78], cell=None),
 ('33a', 'Billing Provider NPI Number'): CellSpec(line=56, field=(33, '33a'), literal='Billing Provider NPI Number', field_type='N', bytes=10, columns=[51, 60], cell=(243, 153)),
 ('33b', 'Billing Provider Qualifier and Legacy Number'): CellSpec(line=56, field=(33, '33b'), literal='Billing Provider Qualifier and Legacy Number', field_type='A/N', bytes=17, columns=[62, 78], cell=(243, 185)),
 ('4', 'Insured Name (Last, First, MI)'): CellSpec(line=5, field=(4, '4'), literal='Insured Name (Last, First, MI)', field_type='A', bytes=29, columns=[50, 78], cell=(39, 151)),
 ('5', "Patient's Address"): CellSpec(line=7, field=(5, '5'), literal="Patient's Address", field_type='A/N', bytes=28, columns=[1, 28], cell=(47, 4)),
 ('5', "Patient's Area Code"): CellSpec(line=11, field=(5, '5'), literal="Patient's Area Code", field_type='N', bytes=3, columns=[15, 17], cell=(64, 45)),
 ('5', "Patient's City"): CellSpec(line=9, field=(5, '5'), literal="Patient's City", field_type='A', bytes=24, columns=[1, 24], cell=(55, 4)),
 ('5', "Patient's Phone Number"): CellSpec(line=11, field=(5, '5'), literal="Patient's Phone Number", field_type='N', bytes=10, columns=[19, 28], cell=(64, 59)),
 ('5', "Patient's State"): CellSpec(line=9, field=(5, '5'), literal="Patient's State", field_type='A', bytes=3, columns=[26, 28], cell=(55, 79)),
 ('5', "Patient's ZIP Code"): CellSpec(line=11, field=(5, '5'), literal="Patient's ZIP Code", field_type='N', bytes=12, columns=[1, 12], cell=(64, 4)),
 ('6', 'Patient Relationship to Insured (Child)'): CellSpec(line=7, field=(6, '6'), literal='Patient Relationship to Insured (Child)', field_type='M', bytes=1, columns=[42], cell=(47, 126)),
 ('6', 'Patient Relationship to Insured (Other)'): CellSpec(line=7, field=(6, '6'), literal='Patient Relationship to Insured (Other)', field_type='M', bytes=1, columns=[47], cell=(47, 141)),
 ('6', 'Patient Relationship to Insured (Self)'): CellSpec(line=7, field=(6, '6'), literal='Patient Relationship to Insured (Self)', field_type='M', bytes=1, columns=[33], cell=(47, 99)),
 ('6', 'Patient Relationship to Insured (Spouse)'): CellSpec(line=7, field=(6, '6'), literal='Patient Relationship to Insured (Spouse)', field_type='M', bytes=1, columns=[38], cell=(47, 114)),
 ('7', "Insured's Address"): CellSpec(line=7, field=(7, '7'), literal="Insured's Address", field_type='A/N', bytes=29, columns=[50, 78], cell=(47, 151)),
 ('7', "Insured's Area Code"): CellSpec(line=11, field=(7, '7'), literal="Insured's Area Code", field_type='N', bytes=3, columns=[65, 67], cell=(64, 195)),
 ('7', "Insured's City"): CellSpec(line=9, field=(7, '7'), literal="Insured's City", field_type='A', bytes=23, columns=[50, 72], cell=(56, 151)),
 ('7', "Insured's Phone Number"): CellSpec(line=11, field=(7, '7'), literal="Insured's Phone Number", field_type='N', bytes=10, columns=[69, 78], cell=(64, 209)),
 ('7', "Insured's State"): CellSpec(line=9, field=(7, '7'), literal="Insured's State", field_type='A', bytes=4, columns=[74, 77], cell=(56, 221)),
 ('7', "Insured's ZIP Code"): CellSpec(line=11, field=(7, '7'), literal="Insured's ZIP Code", field_type='N', bytes=12, columns=[50, 61], cell=(64, 151)),
 ('8', 'Patient Status (Employed)'): CellSpec(line=11, field=(8, '8'), literal='Patient Status (Employed)', field_type='M', bytes=1, columns=[35], cell=(65, 105)),
 ('8', 'Patient Status (Full Time Student)'): CellSpec(line=11, field=(8, '8'), literal='Patient Status (Full Time Student)', field_type='M', bytes=1, columns=[41], cell=(65, 123)),
 ('8', 'Patient Status (Married)'): CellSpec(line=9, field=(8, '8'), literal='Patient Status (Married)', field_type='M', bytes=1, columns=[41], cell=(55, 123)),
 ('8', 'Patient Status (Other)'): CellSpec(line=9, field=(8, '8'), literal='Patient Status (Other)', field_type='M', bytes=1, columns=[47], cell=(55, 141)),
 ('8', 'Patient Status (Part Time Student)'): CellSpec(line=11, field=(8, '8'), literal='Patient Status (Part Time Student)', field_type='M', bytes=1, columns=[47], cell=(65, 141)),
 ('8', 'Patient Status (Single)'): CellSpec(line=9, field=(8, '8'), literal='Patient Status (Single)', field_type='M', bytes=1, columns=[35], cell=(55, 105)),
 ('9', "Other Insured's Name (Last, First, MI)"): CellSpec(line=13, field=(9, '9'), literal="Other Insured's Name (Last, First, MI)", field_type='A', bytes=28, columns=[1, 28], cell=(73, 4)),
 ('9a', "Other Insured's Policy or Group Number"): CellSpec(line=15, field=(9, '9a'), literal="Other Insured's Policy or Group Number", field_type='A/N', bytes=28, columns=[1, 28], cell=(81, 4)),
 ('9b', "Other Insured's Date of Birth (Day)"): CellSpec(line=17, field=(9, '9b'), literal="Other Insured's Date of Birth (Day)", field_type='N', bytes=2, columns=[5, 6], cell=(90, 14)),
 ('9b', "Other Insured's Date of Birth (Month)"): CellSpec(line=17, field=(9, '9b'), literal="Other Insured's Date of Birth (Month)", field_type='N', bytes=2, columns=[2, 3], cell=(90, 5)),
 ('9b', "Other Insured's Date of Birth (Year)"): CellSpec(line=17, field=(9, '9b'), literal="Other Insured's Date of Birth (Year)", field_type='N', bytes=4, columns=[8, 11], cell=(90, 23)),
 ('9b', 'Sex-Female'): CellSpec(line=17, field=(9, '9b'), literal='Sex-Female', field_type='M', bytes=1, columns=[24], cell=(90, 72)),
 ('9b', 'Sex-Male'): CellSpec(line=17, field=(9, '9b'), literal='Sex-Male', field_type='M', bytes=1, columns=[18], cell=(90, 55)),
 ('9c', "Other Insured's Employer's Name or School"): CellSpec(line=19, field=(9, '9c'), literal="Other Insured's Employer's Name or School", field_type='A/N', bytes=28, columns=[1, 28], cell=(98, 4)),
 ('9d', "Other Insured's Insurance Plan Name or PayerID"): CellSpec(line=21, field=(9, '9d'), literal="Other Insured's Insurance Plan Name or PayerID", field_type='A/N', bytes=28, columns=[1, 28], cell=(106, 4))}
